FROM node:8
# Create app directory
WORKDIR /pitch/src/api-gateway
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run-script build
EXPOSE 3000
CMD [ "node", "dist/server.js" ]

# docker build -t pitch/api-gateway .
# docker run -p 49160:3000 -d pitch/api-gateway
# docker ps
# docker logs <guid>