FROM microsoft/dotnet:sdk AS build-env
# Create app directory
WORKDIR /pitch/src/identity

# Copy csproj and restore as distinct layers
COPY Pitch.Identity.Api/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY Pitch.Identity.Api/. ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /pitch/src/identity
COPY --from=build-env /pitch/src/identity/out .
ENTRYPOINT ["dotnet", "Pitch.Identity.Api.dll"]